"""add unique constraint to memories user_id and key

Revision ID: 6351e1420b8a
Revises: 92aa08f433c4
Create Date: 2026-06-21 20:15:00.392752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6351e1420b8a'
down_revision: Union[str, None] = '92aa08f433c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_memories_key', table_name='memories')
    op.create_unique_constraint('uq_memories_user_id_key', 'memories', ['user_id', 'key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_memories_user_id_key', 'memories', type_='unique')
    op.create_index('ix_memories_key', 'memories', ['key'], unique=False)
    # ### end Alembic commands ###
